# Generated by Django 4.2 on 2023-04-08 13:22

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_badge_image_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='date_start',
        ),
        migrations.AddField(
            model_name='quest',
            name='datetime_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 8, 16, 22, 31, 690414), validators=[django.core.validators.MinValueValidator('date_start')]),
        ),
        migrations.AddField(
            model_name='quest',
            name='datetime_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 8, 16, 22, 31, 690414)),
        ),
    ]
