# Generated by Django 4.2 on 2023-04-08 14:55

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_quest_date_end_remove_quest_date_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='datetime_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 8, 17, 55, 12, 271500), validators=[django.core.validators.MinValueValidator('date_start')]),
        ),
        migrations.AlterField(
            model_name='quest',
            name='datetime_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 8, 17, 55, 12, 271500)),
        ),
    ]
