# Generated by Django 4.2 on 2023-04-09 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_quest_datetime_end_alter_quest_datetime_start'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='quest',
            name='datetime_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 18, 4, 5, 806652)),
        ),
        migrations.AlterField(
            model_name='quest',
            name='datetime_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 18, 4, 5, 806652)),
        ),
        migrations.RemoveField(
            model_name='image',
            name='datetime_posted',
        ),
        migrations.RemoveField(
            model_name='image',
            name='posted_by',
        ),
    ]
