# Generated by Django 4.2 on 2023-04-12 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_min_hard_tasks_badge_min_hard_quests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solvedquest',
            name='date_solved',
        ),
        migrations.AddField(
            model_name='solvedquest',
            name='datetime_solved',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 4, 12, 3, 11, 47, 633969)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quest',
            name='datetime_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 3, 11, 22, 102374)),
        ),
        migrations.AlterField(
            model_name='quest',
            name='datetime_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 3, 11, 22, 102374)),
        ),
        migrations.AlterField(
            model_name='rewardrequest',
            name='state',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=1),
        ),
    ]
