# Generated by Django 4.2 on 2023-04-07 09:23

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0002_employee_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(default='email@company.com', max_length=254)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8)])),
                ('date_of_birth', models.DateField(default=datetime.date(1979, 12, 31), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 4, 7))])),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
