# Generated by Django 4.2 on 2023-04-07 22:14

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0003_registerrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='registerrequest',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(1979, 12, 31), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 4, 8))]),
        ),
        migrations.AlterField(
            model_name='registerrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
