# Generated by Django 4.2 on 2023-04-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0004_alter_ownuser_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='registerrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
